# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=0.1.0+79
group=org.hedgetech.waxeverything
java_version=25

# Common
minecraft_version=26.2
minecraft_display_version=26.2.x
mod_name=Wax Everything
mod_author=Jag3Dagster
mod_id=waxeverything
license=GPLv3
credits=Jag3Dagster
description=A Minecraft mod that allows players to apply Honeycomb to (almost) everything.
minecraft_version_range=[26.2, 26.3)

source_url=https://github.com/Hedgehog-Technologies/WaxEverything
issue_url=https://github.com/Hedgehog-Technologies/WaxEverything/issues
homepage_url=https://www.curseforge.com/minecraft/mc-mods/WaxEverything

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Fabric
# https://modmuss50.me/fabric.html
fabric_version=0.153.0+26.2
fabric_loader_version=0.19.0

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=65.0.1
forge_loader_version_range=[65,)

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.7-beta
neoforge_loader_version_range=[4,)

# Yet Another Config Lib
# https://maven.isxander.dev/web/releases/dev/isxander/yet-another-config-lib/
yacl_version=3.9.5+26.2

# Mod Menu
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=20.0.1

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
